[server]
enableStaticServing = true

[[theme.fontFaces]]
family = "SpaceGrotesk"
url = "app/static/SpaceGrotesk-VariableFont_wght.ttf"

[[theme.fontFaces]]
family = "SpaceGroteskHeader"
url = "app/static/SpaceGrotesk-SemiBold.ttf"

[[theme.fontFaces]]
family = "SpaceMono"
url = "app/static/SpaceMono-Bold.ttf"
style = "normal"
weight = 700

[[theme.fontFaces]]
family = "SpaceMono"
url = "app/static/SpaceMono-BoldItalic.ttf"
style = "italic"
weight = 700

[[theme.fontFaces]]
family = "SpaceMono"
url = "app/static/SpaceMono-Italic.ttf"
style = "italic"
weight = 400

[[theme.fontFaces]]
family = "SpaceMono"
url = "app/static/SpaceMono-Regular.ttf"
style = "normal"
weight = 400

[theme]
# Black Gold color scheme
primaryColor = "#FFD700"                    # Gold primary color
backgroundColor = "#0A0A0A"                 # Rich black background
secondaryBackgroundColor = "#1A1A1A"       # Charcoal secondary background
textColor = "#FFFFFF"                       # White text
linkColor = "#FFD700"                       # Gold links
borderColor = "#FFD700"                     # Gold borders
showWidgetBorder = true
baseRadius = "0.8rem"                       # Slightly more rounded corners
font = "SpaceGrotesk"
headingFont = "SpaceGroteskHeader"
codeFont = "SpaceMono"
codeBackgroundColor = "#2D2D2D"            # Dark gray for code blocks
showSidebarBorder = true

[theme.sidebar]
backgroundColor = "#1A1A1A"                 # Dark sidebar background
secondaryBackgroundColor = "#2D2D2D"       # Darker secondary background

# Force dark mode
[theme.base]
dark = true